#include<iostream>
#include<exception>

using namespace std;

class MyException : public exception
{
public:
    const char *what() const throw()
    {
        return "Atteched divide by zero ";
    }
};

int main()
{;

    try
    {
        float x,y;
        cout<<"Enter the two number ";
        cin>>x>>y;
        if(y==0)
        {
            MyException z;
            throw z;
        }
        else
        {
            cout<<"x/y = "<<x/y<<endl;
        }
    }

    catch(exception &e)
    {
        cerr<<e.what()<<endl;
    }

    return 0;

}
